export const labels = {
  ProductName: "Product Name",
  ProductDescription: "Product Description" || "Description",
  ProductAppDescription: "Product App Description" || "Short description",
  ProductStoreDescription: "Product Store Description",
  ProductSKUOrStyle: "Product SKU / Style #" || "SKU",
  ProductBrand: "Product Brand",
  ProductBrandStyle: "Product Brand Style #",
  ProductChargeTaxes: "Product Charge Taxes",
  ProductTaxCode: "Product Tax Code",
  ProductType: "Product Type" || "Type",
  ProductReceived: "Product Received",
  ProductShippingPrice: "Product Shipping Price",
  ProductLowStockLimit: "Product Low Stock Limit",
  ProductSplitByType: "Product Split By Type",
  ProductOptions: "Product Options",
  ProductCategories: "Categories",
  ProductAddons: "Product Addons",
  ProductHideOnWaitlist: "Product Hide On Waitlist",
  ProductBestSelling: "Product Best Selling",
  ProductNotes: "Product Notes",
  ProductImages: "Product Images" || "Images",
  InventoryQuantity: "Inventory Quantity" || "In stock?",
  InventoryColor: "Inventory Color",
  InventorySize: "Inventory Size",
  InventoryWeight: "Inventory Weight" || "Weight (kg)",
  InventoryRetailPrice: "Inventory Retail Price",
  InventorySalePrice: "Inventory Sale Price" || "Sale price",
  InventoryCost: "Inventory Cost" || "Regular price",
  InventoryBarcode: "Inventory Barcode",
  InventorySKU: "Inventory SKU" || "SKU",
  InventoryLength: "Inventory Length" || "Length (cm)",
  InventoryWidth: "Inventory Width" || "Width (cm)",
  InventoryHeight: "Inventory Height" || "Height (cm)",
  InventoryPosition: "Inventory Position",
  InventoryNotes: "Inventory Notes" || "Purchase note",
  InventoryImages: "Inventory Images" || "Images",
};
